def qoshish(a,b):
    return a+b
def ayirish(q,w):
    return q-w
def kopaytirish(r,e):
    return r*e
def bolish(t,u):
    return t/u
def kvadrat(i):
    return i**2  
def kvadrat(o):
    return o**2
def kub(p):
    return p**3
def kub(s):
    return s**3